services:
  apache:
    build:
      context: .
      dockerfile: Dockerfile.apache
    ports:
      - "8080:80"
    depends_on:
      - uwsgi
    networks:
      - vuln-network
    environment:
      - APACHE_LOG_LEVEL=debug
    volumes:
      - ./apache-config:/usr/local/apache2/conf/extra:ro

  uwsgi:
    build:
      context: .
      dockerfile: Dockerfile.uwsgi
    expose:
      - "9090"
    networks:
      - vuln-network
    environment:
      - PYTHONUNBUFFERED=1
      - UWSGI_CHEAPER=0
      - UWSGI_PROCESSES=4

networks:
  vuln-network:
    driver: bridge 